import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  ArrowRight, Check, MapPin, Users, BarChart3, Settings, 
  Layers, Cpu, Database, Calendar, ChevronDown, Mail, 
  Phone, Map, Sparkles, Shield, Clock, ArrowUpRight, Menu, X, Play
} from 'lucide-react';
import { useNavigate } from 'react-router-dom';

export const Landing = () => {
  const navigate = useNavigate();
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const [activeFaq, setActiveFaq] = useState<number | null>(null);

  // Animations config
  const fadeInUp = {
    initial: { opacity: 0, y: 30 },
    whileInView: { opacity: 1, y: 0 },
    viewport: { once: true, margin: "-100px" },
    transition: { duration: 0.6, ease: "easeOut" }
  };

  const staggerContainer = {
    initial: { opacity: 0 },
    whileInView: { opacity: 1 },
    viewport: { once: true, margin: "-100px" },
    transition: { staggerChildren: 0.15 }
  };

  const navLinks = [
    { name: 'Features', href: '#features' },
    { name: 'Statistics', href: '#statistics' },
    { name: 'Workflow', href: '#workflow' },
    { name: 'Timeline', href: '#timeline' },
    { name: 'Advantages', href: '#advantages' },
    { name: 'Preview', href: '#preview' },
    { name: 'FAQs', href: '#faqs' },
    { name: 'Contact', href: '#contact' },
  ];

  const features = [
    {
      icon: <Cpu className="w-6 h-6 text-primary" />,
      title: "AI-Powered Proposal Scoring",
      description: "Instantly evaluate constituency proposals using predictive machine learning models that analyze regional demand, demographics, and feasibility."
    },
    {
      icon: <Layers className="w-6 h-6 text-primary" />,
      title: "Inter-Department Synchronization",
      description: "Break down silos. Automatically cross-reference projects with water, electricity, roads, and forestry departments to prevent overlapping work."
    },
    {
      icon: <Map className="w-6 h-6 text-primary" />,
      title: "GIS Spatial Intelligence",
      description: "Interactive mapping layer automatically flags overlap coordinates and optimizes project distribution based on geographic population densities."
    },
    {
      icon: <Database className="w-6 h-6 text-primary" />,
      title: "Real-time Fund Allocation Tracking",
      description: "Monitor MP Local Area Development (MPLAD) funds with millisecond precision, ensuring transparent budgeting, approvals, and releases."
    },
    {
      icon: <Shield className="w-6 h-6 text-primary" />,
      title: "Sovereign Compliance & Auditing",
      description: "Built-in smart checks align all proposals with national regulatory guidelines and local state development plans automatically."
    },
    {
      icon: <BarChart3 className="w-6 h-6 text-primary" />,
      title: "Predictive Impact Analytics",
      description: "Simulate constituency growth, employment generation, and socio-economic lift before committing capital to a single plan."
    }
  ];

  const stats = [
    { value: "40%", label: "Reduction in Project Delays" },
    { value: "$18.4M", label: "Allocated MPLAD Funds Managed" },
    { value: "12+", label: "Integrated State Departments" },
    { value: "98.9%", label: "Accuracy in Duplication Detection" }
  ];

  const workflowSteps = [
    {
      step: "01",
      title: "Intake & Digitization",
      desc: "Constituency proposals are submitted and digitized via structured OCR. Key parameters such as coordinates, budget, and department are extracted."
    },
    {
      step: "02",
      title: "AI Analysis & Scoring",
      desc: "Our neural network scores the project based on historical success rates, regional urgency metrics, and resource availability."
    },
    {
      step: "03",
      title: "Cross-Department Validation",
      desc: "The system runs a conflict audit against municipal planning layers to ensure zero interference with scheduled public works."
    },
    {
      step: "04",
      title: "Approval & Fund Release",
      desc: "The MP dashboard authorizes the project with cryptographic verification, triggers a direct bank transaction, and publishes to the public portal."
    }
  ];

  const timelines = [
    {
      period: "Week 1",
      title: "Needs Assessment & AI Intake",
      desc: "Citizens submit local issues. System automatically groups adjacent request clusters and builds high-priority proposal drafts."
    },
    {
      period: "Week 2",
      title: "Multi-Department Scrutiny",
      desc: "Parallel workflows route proposals to state engineers and financial controllers for automated impact reports."
    },
    {
      period: "Week 3",
      title: "MP Approval & Allocation",
      desc: "The Member of Parliament reviews optimal scenario reports generated by TechnoSync AI and authorizes top-scoring allocations."
    },
    {
      period: "Week 4+",
      title: "Execution & Real-time Tracking",
      desc: "Contractors submit milestone telemetry. AI flags bottlenecks, manages vendor invoicing, and updates citizens on progress."
    }
  ];

  const advantages = [
    { traditional: "Scattered spreadsheets & paper binders", modern: "Single source of truth cloud data lake" },
    { traditional: "Manual, slow departmental approvals", modern: "Automated, parallel workflow routing" },
    { traditional: "Accidental project overlaps (e.g. road dug up twice)", modern: "GIS-based conflict detection mapping" },
    { traditional: "Obscure budget tracking & citizen distrust", modern: "Public dashboard showing live fund utilization" },
    { traditional: "Reactive, opinion-based planning", modern: "Predictive, demographic-needs-based scoring" }
  ];

  const testimonials = [
    {
      quote: "TechnoSync AI transformed how we coordinate with water and power authorities. We saved nearly 15% of our budget last quarter by catching duplicate pipelines before excavation.",
      author: "Hon. Rajesh Kumar",
      role: "Member of Parliament, North Zone",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=120&h=120&q=80"
    },
    {
      quote: "The GIS duplication detection is a lifesaver. Previously, coordinating with three different departments meant weekly meetings and endless delays. Now it happens in real-time.",
      author: "Priya Sharma",
      role: "Chief Urban Development Commissioner",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=120&h=120&q=80"
    }
  ];

  const faqs = [
    {
      q: "How does the AI verify if a proposal is genuinely needed?",
      a: "TechnoSync AI utilizes satellite imagery, local demographic statistics, regional heatmaps, and citizen ticket counts to rate the social and infrastructural necessity of each proposal."
    },
    {
      q: "Can this system integrate with legacy government databases?",
      a: "Yes. Our platform provides standardized REST APIs and secure file-ingestion connectors designed to sync with state municipal finance systems, national portals, and GIS databases."
    },
    {
      q: "How does the duplicate project detection system work?",
      a: "When a new project is proposed, our spatial analysis engine checks a geo-radius buffer (e.g., 50 meters) against all active and planned works across all participating government departments."
    },
    {
      q: "What security measures protect sensitive development planning?",
      a: "We implement AES-256 encryption at rest, TLS 1.3 in transit, role-based access control (RBAC), and sovereign cloud hosting options that comply with national critical infrastructure standards."
    }
  ];

  return (
    <div className="bg-[#F7F9F8] text-[#4B5563] font-inter overflow-x-hidden min-h-screen">
      
      {/* Sticky Navbar */}
      <header className="sticky top-0 z-50 bg-[#F7F9F8]/80 backdrop-blur-md border-b border-[#DCE5E2] transition-colors">
        <div className="container mx-auto px-6 py-4 flex items-center justify-between">
          <div className="flex items-center space-x-2 cursor-pointer" onClick={() => navigate('/')}>
            <div className="w-10 h-10 rounded-xl bg-gradient-to-tr from-[#2F5D62] to-[#7CC6FE] flex items-center justify-center text-white shadow-md">
              <Sparkles className="w-5 h-5" />
            </div>
            <span className="text-xl font-bold text-[#1F2937] font-poppins">
              TechnoSync <span className="text-[#2F5D62]">AI</span>
            </span>
          </div>

          {/* Desktop Nav Links */}
          <nav className="hidden lg:flex items-center space-x-8">
            {navLinks.map((link) => (
              <a 
                key={link.name} 
                href={link.href} 
                className="text-sm font-medium text-[#4B5563] hover:text-[#2F5D62] transition-colors"
              >
                {link.name}
              </a>
            ))}
          </nav>

          {/* Action Buttons */}
          <div className="hidden lg:flex items-center space-x-4">
            <button 
              onClick={() => navigate('/login')}
              className="text-sm font-semibold text-[#2F5D62] hover:text-[#2F5D62]/80 transition-colors"
            >
              Sign In
            </button>
            <button 
              onClick={() => navigate('/demo')}
              className="bg-gradient-to-r from-[#10B981] to-[#3B82F6] hover:from-[#10B981]/90 hover:to-[#3B82F6]/90 text-white text-sm font-bold px-5 py-2.5 rounded-xl shadow-md transition-all duration-300 hover:shadow-lg flex items-center space-x-2"
            >
              <span>🚀 Demo Command Center</span>
            </button>
            <button 
              onClick={() => navigate('/login')}
              className="bg-[#2F5D62] hover:bg-[#2F5D62]/90 text-white text-sm font-semibold px-5 py-2.5 rounded-xl shadow-md transition-all duration-300 hover:shadow-lg flex items-center space-x-2"
            >
              <span>Launch Platform</span>
              <ArrowRight className="w-4 h-4" />
            </button>
          </div>

          {/* Mobile Menu Button */}
          <button 
            className="lg:hidden p-2 hover:bg-gray-100 rounded-lg text-gray-700"
            onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
          >
            {mobileMenuOpen ? <X className="w-6 h-6" /> : <Menu className="w-6 h-6" />}
          </button>
        </div>

        {/* Mobile Navigation Drawer */}
        <AnimatePresence>
          {mobileMenuOpen && (
            <motion.div 
              initial={{ opacity: 0, height: 0 }}
              animate={{ opacity: 1, height: 'auto' }}
              exit={{ opacity: 0, height: 0 }}
              className="lg:hidden bg-white border-b border-[#DCE5E2] px-6 py-4 space-y-4"
            >
              <nav className="flex flex-col space-y-3">
                {navLinks.map((link) => (
                  <a 
                    key={link.name} 
                    href={link.href} 
                    onClick={() => setMobileMenuOpen(false)}
                    className="text-sm font-medium text-[#4B5563] hover:text-[#2F5D62] transition-colors"
                  >
                    {link.name}
                  </a>
                ))}
              </nav>
              <div className="pt-4 border-t border-gray-100 flex flex-col space-y-3">
                <button 
                  onClick={() => { setMobileMenuOpen(false); navigate('/login'); }}
                  className="w-full text-center py-2.5 text-sm font-semibold text-[#2F5D62]"
                >
                  Sign In
                </button>
                <button 
                  onClick={() => { setMobileMenuOpen(false); navigate('/login'); }}
                  className="w-full bg-[#2F5D62] hover:bg-[#2F5D62]/90 text-white text-center py-2.5 rounded-xl text-sm font-semibold shadow-md"
                >
                  Launch Platform
                </button>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </header>

      {/* Hero Section */}
      <section className="relative overflow-hidden pt-12 pb-24 lg:pt-20 lg:pb-32 bg-gradient-to-b from-[#F7F9F8] via-white to-[#F7F9F8]">
        <div className="absolute top-0 right-0 w-[500px] h-[500px] bg-[#7CC6FE]/10 rounded-full blur-3xl -z-10 pointer-events-none"></div>
        <div className="absolute bottom-0 left-0 w-[400px] h-[400px] bg-[#96ACA0]/10 rounded-full blur-3xl -z-10 pointer-events-none"></div>

        <div className="container mx-auto px-6 grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
          <div className="lg:col-span-6 space-y-8 text-center lg:text-left">
            <motion.div 
              initial={{ opacity: 0, y: -20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5 }}
              className="inline-flex items-center space-x-2 bg-[#2F5D62]/10 text-[#2F5D62] px-3.5 py-1.5 rounded-full text-xs font-semibold tracking-wide"
            >
              <Sparkles className="w-3.5 h-3.5 animate-pulse" />
              <span>Next-Gen MP Development Intelligence Platform</span>
            </motion.div>

            <motion.h1 
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.1 }}
              className="text-4xl sm:text-5xl lg:text-6xl font-extrabold text-[#1F2937] leading-tight font-poppins"
            >
              Accelerate Constituency Growth with <span className="text-[#2F5D62] bg-clip-text">Predictive Planning</span>
            </motion.h1>

            <motion.p 
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.2 }}
              className="text-lg text-[#4B5563] max-w-xl mx-auto lg:mx-0 leading-relaxed"
            >
              TechnoSync AI synchronizes municipal plans, scores development proposals with machine learning, and manages MPLAD funds with transparent, automated governance.
            </motion.p>

            <motion.div 
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.3 }}
              className="flex flex-wrap items-center justify-center lg:justify-start gap-3"
            >
              <button 
                onClick={() => navigate('/demo')}
                className="bg-gradient-to-r from-[#10B981] to-[#3B82F6] hover:from-[#10B981]/90 hover:to-[#3B82F6]/90 text-white font-bold px-8 py-4 rounded-xl shadow-lg transition duration-300 flex items-center space-x-2 text-sm"
              >
                <span>🚀 Launch Demo Command Center</span>
              </button>
              <button 
                onClick={() => navigate('/login')}
                className="bg-[#2F5D62] hover:bg-[#2F5D62]/95 text-white font-semibold px-8 py-4 rounded-xl shadow-lg transition duration-300 flex items-center space-x-2 text-sm border border-[#DCE5E2]"
              >
                <span>Enter Dashboard Portal</span>
                <ArrowRight className="w-4 h-4" />
              </button>
            </motion.div>

            <motion.div 
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ duration: 0.8, delay: 0.4 }}
              className="pt-6 border-t border-[#DCE5E2] grid grid-cols-3 gap-6 text-left max-w-md mx-auto lg:mx-0"
            >
              <div>
                <p className="text-2xl font-bold text-[#1F2937]">99.8%</p>
                <p className="text-xs text-[#4B5563]">Uptime SLA</p>
              </div>
              <div>
                <p className="text-2xl font-bold text-[#1F2937]">Zero</p>
                <p className="text-xs text-[#4B5563]">Overlap Conflicts</p>
              </div>
              <div>
                <p className="text-2xl font-bold text-[#1F2937]">1-Click</p>
                <p className="text-xs text-[#4B5563]">Sovereign Reports</p>
              </div>
            </motion.div>
          </div>

          {/* Interactive Floating Preview Graphic */}
          <motion.div 
            initial={{ opacity: 0, scale: 0.9, x: 50 }}
            animate={{ opacity: 1, scale: 1, x: 0 }}
            transition={{ duration: 0.8, delay: 0.2 }}
            className="lg:col-span-6 relative"
          >
            <div className="relative mx-auto max-w-lg lg:max-w-none bg-white rounded-2xl shadow-2xl border border-[#DCE5E2] overflow-hidden p-3 bg-gradient-to-tr from-white via-white to-[#F7F9F8]">
              {/* Fake Window Header */}
              <div className="flex items-center justify-between pb-3 px-3 border-b border-gray-100 mb-3">
                <div className="flex space-x-1.5">
                  <div className="w-3 h-3 rounded-full bg-red-400"></div>
                  <div className="w-3 h-3 rounded-full bg-yellow-400"></div>
                  <div className="w-3 h-3 rounded-full bg-green-400"></div>
                </div>
                <div className="bg-gray-100 text-[10px] px-8 py-0.5 rounded text-gray-500 font-mono">
                  platform.technosync.ai/dashboard
                </div>
                <div className="w-4"></div>
              </div>

              {/* Fake Dashboard Content */}
              <div className="space-y-4">
                <div className="grid grid-cols-3 gap-3">
                  <div className="bg-[#2F5D62]/5 border border-[#2F5D62]/10 p-3 rounded-xl">
                    <p className="text-[10px] uppercase font-bold text-[#2F5D62]">Total Budget</p>
                    <p className="text-lg font-bold text-[#1F2937] mt-0.5">$5.2M</p>
                    <div className="w-full bg-gray-200 h-1.5 rounded-full mt-2 overflow-hidden">
                      <div className="bg-[#2F5D62] h-full rounded-full" style={{ width: '70%' }}></div>
                    </div>
                  </div>
                  <div className="bg-[#7CC6FE]/5 border border-[#7CC6FE]/10 p-3 rounded-xl">
                    <p className="text-[10px] uppercase font-bold text-[#7CC6FE] dark:text-[#2F5D62]">Approved Proposals</p>
                    <p className="text-lg font-bold text-[#1F2937] mt-0.5">84</p>
                    <p className="text-[9px] text-[#96ACA0] mt-2 flex items-center">
                      <span className="w-1.5 h-1.5 rounded-full bg-green-500 mr-1"></span> Active
                    </p>
                  </div>
                  <div className="bg-amber-50 border border-amber-200 p-3 rounded-xl">
                    <p className="text-[10px] uppercase font-bold text-amber-600">Conflict Audits</p>
                    <p className="text-lg font-bold text-amber-700 mt-0.5">0 Pending</p>
                    <p className="text-[9px] text-green-600 mt-2 flex items-center font-semibold">
                      <Check className="w-3 h-3 mr-0.5" /> Checked
                    </p>
                  </div>
                </div>

                {/* Simulated Chart/Map UI */}
                <div className="grid grid-cols-12 gap-3">
                  <div className="col-span-8 bg-gray-50 border border-gray-100 p-3 rounded-xl h-44 flex flex-col justify-between">
                    <div className="flex items-center justify-between">
                      <p className="text-[11px] font-bold text-[#1F2937]">Regional Resource Scoring</p>
                      <span className="text-[9px] bg-white px-2 py-0.5 rounded border text-gray-500 font-medium">Last 30 Days</span>
                    </div>
                    {/* Simulated Bars */}
                    <div className="flex items-end justify-between h-28 pt-2">
                      <div className="w-6 bg-[#2F5D62] rounded-t-sm" style={{ height: '35%' }}></div>
                      <div className="w-6 bg-[#2F5D62] rounded-t-sm" style={{ height: '65%' }}></div>
                      <div className="w-6 bg-[#7CC6FE] rounded-t-sm" style={{ height: '85%' }}></div>
                      <div className="w-6 bg-[#2F5D62] rounded-t-sm" style={{ height: '40%' }}></div>
                      <div className="w-6 bg-[#96ACA0] rounded-t-sm" style={{ height: '90%' }}></div>
                      <div className="w-6 bg-[#2F5D62] rounded-t-sm" style={{ height: '55%' }}></div>
                    </div>
                  </div>

                  <div className="col-span-4 bg-gray-50 border border-gray-100 p-3 rounded-xl flex flex-col justify-between">
                    <p className="text-[11px] font-bold text-[#1F2937]">Conflict Map</p>
                    <div className="w-full bg-gray-200 h-28 rounded-lg overflow-hidden relative flex items-center justify-center border border-gray-300">
                      {/* Abstract Grid Map */}
                      <div className="absolute inset-0 bg-blue-50/50 grid grid-cols-4 grid-rows-4">
                        {[...Array(16)].map((_, i) => (
                          <div key={i} className="border-[0.5px] border-blue-100/50"></div>
                        ))}
                      </div>
                      <div className="w-3 h-3 rounded-full bg-[#2F5D62] absolute top-1/3 left-1/3 animate-ping"></div>
                      <div className="w-2.5 h-2.5 rounded-full bg-[#2F5D62] absolute top-1/3 left-1/3"></div>
                      <div className="w-2 h-2 rounded-full bg-amber-400 absolute bottom-1/4 right-1/3"></div>
                      <MapPin className="w-5 h-5 text-red-500 absolute top-1/2 right-1/4" />
                      <span className="text-[9px] font-mono text-gray-500 absolute bottom-1 right-1 bg-white/80 px-1 rounded">28.6°N</span>
                    </div>
                    <div className="text-[9px] text-gray-500 flex items-center justify-between mt-1">
                      <span>Sync status</span>
                      <span className="text-green-600 font-semibold flex items-center">
                        <span className="w-1 h-1 rounded-full bg-green-500 mr-1 animate-pulse"></span> Connected
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {/* Decors */}
            <div className="absolute -top-4 -right-4 w-12 h-12 bg-yellow-400/20 rounded-full blur-md animate-bounce" style={{ animationDuration: '3s' }}></div>
          </motion.div>
        </div>
      </section>

      {/* Features Section */}
      <section id="features" className="py-24 bg-white border-t border-b border-[#DCE5E2]">
        <div className="container mx-auto px-6">
          <div className="text-center max-w-3xl mx-auto space-y-4 mb-20">
            <h2 className="text-xs uppercase tracking-widest font-extrabold text-[#2F5D62]">Dynamic Capabilities</h2>
            <p className="text-3xl sm:text-4xl font-extrabold text-[#1F2937] font-poppins">Built to Orchestrate Local Infrastructure Scenarios</p>
            <p className="text-md text-[#4B5563]">
              Remove the guesswork from regional budget planning. Standardize approvals and ensure spatial transparency.
            </p>
          </div>

          <motion.div 
            variants={staggerContainer}
            initial="initial"
            whileInView="whileInView"
            className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8"
          >
            {features.map((feat, index) => (
              <motion.div 
                key={index} 
                variants={fadeInUp}
                className="bg-[#F7F9F8] border border-[#DCE5E2] hover:border-[#7CC6FE] p-8 rounded-2xl transition-all duration-300 hover:shadow-lg group"
              >
                <div className="w-12 h-12 rounded-xl bg-white border border-[#DCE5E2] flex items-center justify-center shadow-sm group-hover:scale-110 transition-transform duration-300">
                  {feat.icon}
                </div>
                <h3 className="text-lg font-bold text-[#1F2937] mt-6 mb-3 font-poppins">{feat.title}</h3>
                <p className="text-sm text-[#4B5563] leading-relaxed">{feat.description}</p>
              </motion.div>
            ))}
          </motion.div>
        </div>
      </section>

      {/* Statistics Section */}
      <section id="statistics" className="py-24 bg-gradient-to-br from-[#2F5D62] to-[#1F2937] text-white">
        <div className="container mx-auto px-6">
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-8 text-center">
            {stats.map((st, index) => (
              <motion.div 
                key={index}
                initial={{ opacity: 0, scale: 0.8 }}
                whileInView={{ opacity: 1, scale: 1 }}
                viewport={{ once: true }}
                transition={{ duration: 0.5, delay: index * 0.1 }}
                className="space-y-2"
              >
                <p className="text-4xl sm:text-5xl lg:text-6xl font-extrabold font-poppins text-[#7CC6FE]">{st.value}</p>
                <p className="text-sm sm:text-md text-[#96ACA0] font-medium max-w-[200px] mx-auto leading-tight">{st.label}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* AI Workflow Section */}
      <section id="workflow" className="py-24 bg-[#F7F9F8]">
        <div className="container mx-auto px-6">
          <div className="text-center max-w-3xl mx-auto space-y-4 mb-20">
            <h2 className="text-xs uppercase tracking-widest font-extrabold text-[#2F5D62]">Workflow Pipeline</h2>
            <p className="text-3xl sm:text-4xl font-extrabold text-[#1F2937] font-poppins">The Lifecycle of a Smart Proposal</p>
            <p className="text-md text-[#4B5563]">
              From the initial citizen submission to transaction reconciliation, see how intelligence is injected at every step.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8 relative">
            {workflowSteps.map((step, index) => (
              <motion.div 
                key={index}
                initial={{ opacity: 0, y: 40 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.6, delay: index * 0.15 }}
                className="bg-white border border-[#DCE5E2] p-8 rounded-2xl relative shadow-sm group hover:shadow-md transition-shadow"
              >
                <span className="text-5xl font-extrabold text-[#2F5D62]/10 absolute top-4 right-6 font-poppins select-none group-hover:text-[#2F5D62]/20 transition-colors">
                  {step.step}
                </span>
                <h3 className="text-lg font-bold text-[#1F2937] mb-4 mt-2 font-poppins">{step.title}</h3>
                <p className="text-sm text-[#4B5563] leading-relaxed">{step.desc}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Timeline Section */}
      <section id="timeline" className="py-24 bg-white border-t border-b border-[#DCE5E2]">
        <div className="container mx-auto px-6">
          <div className="text-center max-w-3xl mx-auto space-y-4 mb-20">
            <h2 className="text-xs uppercase tracking-widest font-extrabold text-[#2F5D62]">Standard Timeline</h2>
            <p className="text-3xl sm:text-4xl font-extrabold text-[#1F2937] font-poppins">Rapid 30-Day Project Turnaround</p>
            <p className="text-md text-[#4B5563]">
              How TechnoSync AI compresses months of red tape, validation cycles, and public hearings into a structured sprint.
            </p>
          </div>

          <div className="max-w-4xl mx-auto relative border-l border-[#DCE5E2] pl-8 space-y-12">
            {timelines.map((tl, index) => (
              <motion.div 
                key={index}
                initial={{ opacity: 0, x: -30 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.5, delay: index * 0.15 }}
                className="relative"
              >
                <div className="absolute -left-[41px] top-1.5 w-6 h-6 rounded-full bg-white border-4 border-[#2F5D62] flex items-center justify-center">
                  <div className="w-1.5 h-1.5 rounded-full bg-[#2F5D62]"></div>
                </div>
                <div className="bg-[#F7F9F8] border border-[#DCE5E2] p-6 rounded-xl space-y-2">
                  <span className="text-xs font-extrabold text-[#2F5D62] uppercase tracking-wider">{tl.period}</span>
                  <h3 className="text-lg font-bold text-[#1F2937] font-poppins">{tl.title}</h3>
                  <p className="text-sm text-[#4B5563] leading-relaxed">{tl.desc}</p>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Advantages Section */}
      <section id="advantages" className="py-24 bg-[#F7F9F8]">
        <div className="container mx-auto px-6">
          <div className="text-center max-w-3xl mx-auto space-y-4 mb-20">
            <h2 className="text-xs uppercase tracking-widest font-extrabold text-[#2F5D62]">The Competitive Edge</h2>
            <p className="text-3xl sm:text-4xl font-extrabold text-[#1F2937] font-poppins">Legacy Methods vs. TechnoSync AI</p>
            <p className="text-md text-[#4B5563]">
              Why leading constituencies are upgrading from legacy tools to continuous spatial audit cycles.
            </p>
          </div>

          <div className="max-w-4xl mx-auto bg-white border border-[#DCE5E2] rounded-2xl overflow-hidden shadow-sm">
            <div className="grid grid-cols-2 bg-[#2F5D62] text-white p-4 font-bold text-sm sm:text-base font-poppins">
              <div className="px-4">Legacy Process</div>
              <div className="px-4 border-l border-white/20">TechnoSync AI Platform</div>
            </div>
            <div className="divide-y divide-[#DCE5E2]">
              {advantages.map((adv, index) => (
                <div key={index} className="grid grid-cols-2 p-5 text-xs sm:text-sm">
                  <div className="px-4 text-red-500 flex items-start space-x-2">
                    <span className="mt-0.5 select-none">✕</span>
                    <span>{adv.traditional}</span>
                  </div>
                  <div className="px-4 border-l border-[#DCE5E2] text-green-700 flex items-start space-x-2 font-medium">
                    <span className="mt-0.5 text-[#2F5D62] select-none">✓</span>
                    <span>{adv.modern}</span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Screenshots Section / Interactive Preview */}
      <section id="preview" className="py-24 bg-white border-t border-b border-[#DCE5E2]">
        <div className="container mx-auto px-6">
          <div className="text-center max-w-3xl mx-auto space-y-4 mb-16">
            <h2 className="text-xs uppercase tracking-widest font-extrabold text-[#2F5D62]">System Preview</h2>
            <p className="text-3xl sm:text-4xl font-extrabold text-[#1F2937] font-poppins">A Unified Sovereign Workspace</p>
            <p className="text-md text-[#4B5563]">
              An intuitive interface tailored for high-velocity civil decisions. Experience Stripe-like clarity.
            </p>
          </div>

          <motion.div 
            initial={{ opacity: 0, y: 50 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.8 }}
            className="bg-[#1F2937] rounded-3xl p-4 sm:p-6 shadow-2xl border border-gray-700 overflow-hidden"
          >
            {/* Window Frame */}
            <div className="bg-gray-800 rounded-2xl overflow-hidden border border-gray-700">
              <div className="bg-gray-900 px-4 py-3 flex items-center justify-between border-b border-gray-800">
                <div className="flex space-x-1.5">
                  <div className="w-3 h-3 rounded-full bg-red-500/80"></div>
                  <div className="w-3 h-3 rounded-full bg-yellow-500/80"></div>
                  <div className="w-3 h-3 rounded-full bg-green-500/80"></div>
                </div>
                <span className="text-xs text-gray-500 font-mono">dashboard.technosync.ai/proposals</span>
                <ArrowUpRight className="w-4 h-4 text-gray-500" />
              </div>
              <div className="p-4 sm:p-8 bg-gray-950 text-gray-300 min-h-[400px] space-y-6">
                <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 pb-6 border-b border-gray-800">
                  <div>
                    <h3 className="text-xl font-bold text-white font-poppins">Constituency Proposal Registry</h3>
                    <p className="text-xs text-gray-500 mt-1">Filters: Area A-1, High Priority Scoring</p>
                  </div>
                  <button className="bg-[#2F5D62] text-white px-4 py-2 rounded-lg text-xs font-semibold hover:bg-[#2F5D62]/90 transition">
                    + Create Proposal
                  </button>
                </div>

                <div className="overflow-x-auto">
                  <table className="w-full text-left border-collapse text-xs sm:text-sm">
                    <thead>
                      <tr className="border-b border-gray-800 text-gray-500 uppercase tracking-wider text-[10px]">
                        <th className="py-3 px-4">Proposal Reference</th>
                        <th className="py-3 px-4">Sector</th>
                        <th className="py-3 px-4">Score</th>
                        <th className="py-3 px-4">Budget</th>
                        <th className="py-3 px-4">Status</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-gray-800/50">
                      <tr>
                        <td className="py-4 px-4 font-semibold text-white">#PROP-2026-092</td>
                        <td className="py-4 px-4">Rural Drinking Water Pipeline</td>
                        <td className="py-4 px-4 text-[#7CC6FE] font-bold">96/100</td>
                        <td className="py-4 px-4">$450,000</td>
                        <td className="py-4 px-4">
                          <span className="bg-green-500/10 text-green-400 px-2.5 py-1 rounded-full text-xs font-semibold">Approved</span>
                        </td>
                      </tr>
                      <tr>
                        <td className="py-4 px-4 font-semibold text-white">#PROP-2026-081</td>
                        <td className="py-4 px-4">High School Smart Labs</td>
                        <td className="py-4 px-4 text-[#7CC6FE] font-bold">89/100</td>
                        <td className="py-4 px-4">$120,000</td>
                        <td className="py-4 px-4">
                          <span className="bg-yellow-500/10 text-yellow-400 px-2.5 py-1 rounded-full text-xs font-semibold">Under Audit</span>
                        </td>
                      </tr>
                      <tr>
                        <td className="py-4 px-4 font-semibold text-white">#PROP-2026-074</td>
                        <td className="py-4 px-4">Solar Street Lighting G-3</td>
                        <td className="py-4 px-4 text-[#7CC6FE] font-bold">91/100</td>
                        <td className="py-4 px-4">$85,000</td>
                        <td className="py-4 px-4">
                          <span className="bg-[#2F5D62]/20 text-[#7CC6FE] px-2.5 py-1 rounded-full text-xs font-semibold">Synced</span>
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </motion.div>
        </div>
      </section>

      {/* Testimonials Section */}
      <section className="py-24 bg-[#F7F9F8]">
        <div className="container mx-auto px-6">
          <div className="text-center max-w-3xl mx-auto space-y-4 mb-20">
            <h2 className="text-xs uppercase tracking-widest font-extrabold text-[#2F5D62]">Client Testimonials</h2>
            <p className="text-3xl sm:text-4xl font-extrabold text-[#1F2937] font-poppins">Endorsed by Civic Planners</p>
            <p className="text-md text-[#4B5563]">
              Read how members of legislative committees evaluate their experience transitioning from sheets to automated workflows.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 max-w-5xl mx-auto">
            {testimonials.map((test, index) => (
              <motion.div 
                key={index}
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.6, delay: index * 0.15 }}
                className="bg-white border border-[#DCE5E2] p-8 rounded-2xl shadow-sm flex flex-col justify-between"
              >
                <p className="text-md italic text-[#4B5563] leading-relaxed mb-6">
                  "{test.quote}"
                </p>
                <div className="flex items-center space-x-4">
                  <img 
                    src={test.avatar} 
                    alt={test.author} 
                    className="w-12 h-12 rounded-full object-cover border-2 border-[#DCE5E2]"
                  />
                  <div>
                    <h4 className="font-bold text-[#1F2937] font-poppins">{test.author}</h4>
                    <p className="text-xs text-[#96ACA0] font-semibold">{test.role}</p>
                  </div>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* FAQs Section */}
      <section id="faqs" className="py-24 bg-white border-t border-b border-[#DCE5E2]">
        <div className="container mx-auto px-6">
          <div className="text-center max-w-3xl mx-auto space-y-4 mb-20">
            <h2 className="text-xs uppercase tracking-widest font-extrabold text-[#2F5D62]">Support Center</h2>
            <p className="text-3xl sm:text-4xl font-extrabold text-[#1F2937] font-poppins">Frequently Asked Questions</p>
            <p className="text-md text-[#4B5563]">
              Clear, precise explanations of how TechnoSync AI operates and integrates.
            </p>
          </div>

          <div className="max-w-3xl mx-auto divide-y divide-[#DCE5E2]">
            {faqs.map((faq, index) => (
              <div key={index} className="py-5">
                <button 
                  className="w-full flex items-center justify-between py-3 text-left font-semibold text-[#1F2937] hover:text-[#2F5D62] transition-colors font-poppins focus:outline-none"
                  onClick={() => setActiveFaq(activeFaq === index ? null : index)}
                >
                  <span>{faq.q}</span>
                  <ChevronDown className={`w-5 h-5 text-gray-400 transform transition-transform duration-300 ${activeFaq === index ? 'rotate-180 text-[#2F5D62]' : ''}`} />
                </button>
                <AnimatePresence initial={false}>
                  {activeFaq === index && (
                    <motion.div 
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: 'auto', opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      transition={{ duration: 0.3 }}
                      className="overflow-hidden"
                    >
                      <p className="text-sm text-[#4B5563] leading-relaxed pt-2 pb-4 pl-1">
                        {faq.a}
                      </p>
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Contact Section */}
      <section id="contact" className="py-24 bg-[#F7F9F8]">
        <div className="container mx-auto px-6">
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 max-w-6xl mx-auto items-stretch">
            <div className="lg:col-span-5 bg-gradient-to-tr from-[#2F5D62] to-[#1F2937] text-white p-10 rounded-3xl flex flex-col justify-between space-y-12">
              <div className="space-y-4">
                <h3 className="text-2xl font-bold font-poppins">Get in Touch</h3>
                <p className="text-sm text-[#96ACA0]">
                  Schedule a private demo or request access to sovereign hosting deployments.
                </p>
              </div>

              <div className="space-y-6">
                <div className="flex items-center space-x-4">
                  <Mail className="w-5 h-5 text-[#7CC6FE]" />
                  <span className="text-sm">procurement@technosync.ai</span>
                </div>
                <div className="flex items-center space-x-4">
                  <Phone className="w-5 h-5 text-[#7CC6FE]" />
                  <span className="text-sm">+1 (800) 555-0199</span>
                </div>
                <div className="flex items-center space-x-4">
                  <MapPin className="w-5 h-5 text-[#7CC6FE]" />
                  <span className="text-sm">750 Constitution Ave, Suite 400, Washington, DC</span>
                </div>
              </div>

              <div className="pt-6 border-t border-white/10 text-xs text-[#96ACA0]">
                Sovereign planning audits typically deploy in 14 business days.
              </div>
            </div>

            <div className="lg:col-span-7 bg-white p-10 rounded-3xl border border-[#DCE5E2] shadow-sm">
              <form className="space-y-6" onSubmit={(e) => e.preventDefault()}>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
                  <div>
                    <label className="block text-xs uppercase tracking-wider font-extrabold text-[#1F2937] mb-2">First Name</label>
                    <input 
                      type="text" 
                      placeholder="Alexander"
                      className="w-full bg-gray-50 border border-[#DCE5E2] rounded-xl px-4 py-3 text-sm focus:outline-none focus:border-[#2F5D62] transition"
                    />
                  </div>
                  <div>
                    <label className="block text-xs uppercase tracking-wider font-extrabold text-[#1F2937] mb-2">Last Name</label>
                    <input 
                      type="text" 
                      placeholder="Hamilton"
                      className="w-full bg-gray-50 border border-[#DCE5E2] rounded-xl px-4 py-3 text-sm focus:outline-none focus:border-[#2F5D62] transition"
                    />
                  </div>
                </div>

                <div>
                  <label className="block text-xs uppercase tracking-wider font-extrabold text-[#1F2937] mb-2">Government Email</label>
                  <input 
                    type="email" 
                    placeholder="hamilton@treasury.gov"
                    className="w-full bg-gray-50 border border-[#DCE5E2] rounded-xl px-4 py-3 text-sm focus:outline-none focus:border-[#2F5D62] transition"
                  />
                </div>

                <div>
                  <label className="block text-xs uppercase tracking-wider font-extrabold text-[#1F2937] mb-2">Department / Agency</label>
                  <input 
                    type="text" 
                    placeholder="Department of Infrastructure & Logistics"
                    className="w-full bg-gray-50 border border-[#DCE5E2] rounded-xl px-4 py-3 text-sm focus:outline-none focus:border-[#2F5D62] transition"
                  />
                </div>

                <div>
                  <label className="block text-xs uppercase tracking-wider font-extrabold text-[#1F2937] mb-2">Message</label>
                  <textarea 
                    rows={4}
                    placeholder="Describe your constituency demands or custom telemetry requirements..."
                    className="w-full bg-gray-50 border border-[#DCE5E2] rounded-xl px-4 py-3 text-sm focus:outline-none focus:border-[#2F5D62] transition resize-none"
                  ></textarea>
                </div>

                <button 
                  type="submit"
                  className="w-full bg-[#2F5D62] hover:bg-[#2F5D62]/95 text-white font-semibold py-3.5 rounded-xl shadow-md transition duration-300 flex items-center justify-center space-x-2"
                >
                  <span>Submit Demo Request</span>
                  <ArrowRight className="w-4 h-4" />
                </button>
              </form>
            </div>
          </div>
        </div>
      </section>

      {/* Footer Section */}
      <footer className="bg-white border-t border-[#DCE5E2] pt-16 pb-8">
        <div className="container mx-auto px-6 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-12 pb-12 border-b border-gray-100">
          <div className="lg:col-span-2 space-y-6">
            <div className="flex items-center space-x-2">
              <div className="w-8 h-8 rounded-lg bg-gradient-to-tr from-[#2F5D62] to-[#7CC6FE] flex items-center justify-center text-white">
                <Sparkles className="w-4 h-4" />
              </div>
              <span className="text-lg font-bold text-[#1F2937] font-poppins">TechnoSync AI</span>
            </div>
            <p className="text-sm text-[#4B5563] max-w-sm leading-relaxed">
              Standardizing Member of Legislative planning workflows. Secure, auditable, and built for sovereign infrastructure.
            </p>
            <div className="flex items-center space-x-4">
              <span className="text-xs bg-[#2F5D62]/10 text-[#2F5D62] font-semibold px-2.5 py-1 rounded">FedRAMP Ready</span>
              <span className="text-xs bg-gray-100 text-gray-500 font-semibold px-2.5 py-1 rounded">SOC 2 Type II</span>
            </div>
          </div>

          <div>
            <h4 className="text-xs uppercase tracking-wider font-extrabold text-[#1F2937] mb-4 font-poppins">Product</h4>
            <ul className="space-y-3 text-sm">
              <li><a href="#features" className="hover:text-[#2F5D62] transition-colors">Features</a></li>
              <li><a href="#workflow" className="hover:text-[#2F5D62] transition-colors">AI Engine</a></li>
              <li><a href="#preview" className="hover:text-[#2F5D62] transition-colors">Integrations</a></li>
              <li><a href="#" className="hover:text-[#2F5D62] transition-colors">Security Audit</a></li>
            </ul>
          </div>

          <div>
            <h4 className="text-xs uppercase tracking-wider font-extrabold text-[#1F2937] mb-4 font-poppins">Company</h4>
            <ul className="space-y-3 text-sm">
              <li><a href="#timeline" className="hover:text-[#2F5D62] transition-colors">Timeline</a></li>
              <li><a href="#advantages" className="hover:text-[#2F5D62] transition-colors">Comparison</a></li>
              <li><a href="#faqs" className="hover:text-[#2F5D62] transition-colors">FAQs</a></li>
              <li><a href="#contact" className="hover:text-[#2F5D62] transition-colors">Inquiries</a></li>
            </ul>
          </div>

          <div>
            <h4 className="text-xs uppercase tracking-wider font-extrabold text-[#1F2937] mb-4 font-poppins">Newsletter</h4>
            <p className="text-xs text-[#4B5563] mb-4">Receive monthly reports on regional planning optimizations.</p>
            <form className="flex space-x-2" onSubmit={(e) => e.preventDefault()}>
              <input 
                type="email" 
                placeholder="you@agency.gov"
                className="bg-gray-50 border border-[#DCE5E2] rounded-lg px-3 py-2 text-xs focus:outline-none focus:border-[#2F5D62] flex-1"
              />
              <button type="submit" className="bg-[#2F5D62] text-white px-3 py-2 rounded-lg text-xs font-semibold hover:bg-[#2F5D62]/90">
                Join
              </button>
            </form>
          </div>
        </div>

        <div className="container mx-auto px-6 pt-8 flex flex-col sm:flex-row items-center justify-between text-xs text-gray-500 gap-4">
          <span>&copy; {new Date().getFullYear()} TechnoSync AI. All rights reserved.</span>
          <div className="flex space-x-6">
            <a href="#" className="hover:underline">Privacy Policy</a>
            <a href="#" className="hover:underline">Terms of Service</a>
            <a href="#" className="hover:underline">Sovereign Compliance</a>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default Landing;
